// Code generated by protoc-gen-go. DO NOT EDIT.
// source: orderpb/order.proto

package orderpb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type LocalCut struct {
	ShardID              int32    `protobuf:"varint,1,opt,name=shardID,proto3" json:"shardID,omitempty"`
	LocalReplicaID       int32    `protobuf:"varint,2,opt,name=localReplicaID,proto3" json:"localReplicaID,omitempty"`
	Cut                  []int64  `protobuf:"varint,3,rep,packed,name=cut,proto3" json:"cut,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LocalCut) Reset()         { *m = LocalCut{} }
func (m *LocalCut) String() string { return proto.CompactTextString(m) }
func (*LocalCut) ProtoMessage()    {}
func (*LocalCut) Descriptor() ([]byte, []int) {
	return fileDescriptor_87a9833f63666870, []int{0}
}

func (m *LocalCut) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LocalCut.Unmarshal(m, b)
}
func (m *LocalCut) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LocalCut.Marshal(b, m, deterministic)
}
func (m *LocalCut) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LocalCut.Merge(m, src)
}
func (m *LocalCut) XXX_Size() int {
	return xxx_messageInfo_LocalCut.Size(m)
}
func (m *LocalCut) XXX_DiscardUnknown() {
	xxx_messageInfo_LocalCut.DiscardUnknown(m)
}

var xxx_messageInfo_LocalCut proto.InternalMessageInfo

func (m *LocalCut) GetShardID() int32 {
	if m != nil {
		return m.ShardID
	}
	return 0
}

func (m *LocalCut) GetLocalReplicaID() int32 {
	if m != nil {
		return m.LocalReplicaID
	}
	return 0
}

func (m *LocalCut) GetCut() []int64 {
	if m != nil {
		return m.Cut
	}
	return nil
}

type LocalCuts struct {
	Cuts                 []*LocalCut `protobuf:"bytes,1,rep,name=cuts,proto3" json:"cuts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *LocalCuts) Reset()         { *m = LocalCuts{} }
func (m *LocalCuts) String() string { return proto.CompactTextString(m) }
func (*LocalCuts) ProtoMessage()    {}
func (*LocalCuts) Descriptor() ([]byte, []int) {
	return fileDescriptor_87a9833f63666870, []int{1}
}

func (m *LocalCuts) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LocalCuts.Unmarshal(m, b)
}
func (m *LocalCuts) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LocalCuts.Marshal(b, m, deterministic)
}
func (m *LocalCuts) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LocalCuts.Merge(m, src)
}
func (m *LocalCuts) XXX_Size() int {
	return xxx_messageInfo_LocalCuts.Size(m)
}
func (m *LocalCuts) XXX_DiscardUnknown() {
	xxx_messageInfo_LocalCuts.DiscardUnknown(m)
}

var xxx_messageInfo_LocalCuts proto.InternalMessageInfo

func (m *LocalCuts) GetCuts() []*LocalCut {
	if m != nil {
		return m.Cuts
	}
	return nil
}

type CommittedCut struct {
	StartGSN int64 `protobuf:"varint,1,opt,name=startGSN,proto3" json:"startGSN,omitempty"`
	// from globalReplicaID to each cut entry
	// globalReplicaID = shardID * numReplicas + localReplicaID
	Cut                  map[int32]int64 `protobuf:"bytes,2,rep,name=cut,proto3" json:"cut,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *CommittedCut) Reset()         { *m = CommittedCut{} }
func (m *CommittedCut) String() string { return proto.CompactTextString(m) }
func (*CommittedCut) ProtoMessage()    {}
func (*CommittedCut) Descriptor() ([]byte, []int) {
	return fileDescriptor_87a9833f63666870, []int{2}
}

func (m *CommittedCut) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommittedCut.Unmarshal(m, b)
}
func (m *CommittedCut) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommittedCut.Marshal(b, m, deterministic)
}
func (m *CommittedCut) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommittedCut.Merge(m, src)
}
func (m *CommittedCut) XXX_Size() int {
	return xxx_messageInfo_CommittedCut.Size(m)
}
func (m *CommittedCut) XXX_DiscardUnknown() {
	xxx_messageInfo_CommittedCut.DiscardUnknown(m)
}

var xxx_messageInfo_CommittedCut proto.InternalMessageInfo

func (m *CommittedCut) GetStartGSN() int64 {
	if m != nil {
		return m.StartGSN
	}
	return 0
}

func (m *CommittedCut) GetCut() map[int32]int64 {
	if m != nil {
		return m.Cut
	}
	return nil
}

type CommittedEntry struct {
	Seq                  int64          `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`
	ViewID               int32          `protobuf:"varint,2,opt,name=viewID,proto3" json:"viewID,omitempty"`
	CommittedCut         *CommittedCut  `protobuf:"bytes,3,opt,name=committedCut,proto3" json:"committedCut,omitempty"`
	FinalizeShards       *FinalizeEntry `protobuf:"bytes,4,opt,name=finalizeShards,proto3" json:"finalizeShards,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *CommittedEntry) Reset()         { *m = CommittedEntry{} }
func (m *CommittedEntry) String() string { return proto.CompactTextString(m) }
func (*CommittedEntry) ProtoMessage()    {}
func (*CommittedEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_87a9833f63666870, []int{3}
}

func (m *CommittedEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommittedEntry.Unmarshal(m, b)
}
func (m *CommittedEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommittedEntry.Marshal(b, m, deterministic)
}
func (m *CommittedEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommittedEntry.Merge(m, src)
}
func (m *CommittedEntry) XXX_Size() int {
	return xxx_messageInfo_CommittedEntry.Size(m)
}
func (m *CommittedEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_CommittedEntry.DiscardUnknown(m)
}

var xxx_messageInfo_CommittedEntry proto.InternalMessageInfo

func (m *CommittedEntry) GetSeq() int64 {
	if m != nil {
		return m.Seq
	}
	return 0
}

func (m *CommittedEntry) GetViewID() int32 {
	if m != nil {
		return m.ViewID
	}
	return 0
}

func (m *CommittedEntry) GetCommittedCut() *CommittedCut {
	if m != nil {
		return m.CommittedCut
	}
	return nil
}

func (m *CommittedEntry) GetFinalizeShards() *FinalizeEntry {
	if m != nil {
		return m.FinalizeShards
	}
	return nil
}

type FinalizeEntry struct {
	Limit                int32    `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	ShardIDs             []int32  `protobuf:"varint,2,rep,packed,name=shardIDs,proto3" json:"shardIDs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FinalizeEntry) Reset()         { *m = FinalizeEntry{} }
func (m *FinalizeEntry) String() string { return proto.CompactTextString(m) }
func (*FinalizeEntry) ProtoMessage()    {}
func (*FinalizeEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_87a9833f63666870, []int{4}
}

func (m *FinalizeEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FinalizeEntry.Unmarshal(m, b)
}
func (m *FinalizeEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FinalizeEntry.Marshal(b, m, deterministic)
}
func (m *FinalizeEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FinalizeEntry.Merge(m, src)
}
func (m *FinalizeEntry) XXX_Size() int {
	return xxx_messageInfo_FinalizeEntry.Size(m)
}
func (m *FinalizeEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_FinalizeEntry.DiscardUnknown(m)
}

var xxx_messageInfo_FinalizeEntry proto.InternalMessageInfo

func (m *FinalizeEntry) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *FinalizeEntry) GetShardIDs() []int32 {
	if m != nil {
		return m.ShardIDs
	}
	return nil
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_87a9833f63666870, []int{5}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

func init() {
	proto.RegisterType((*LocalCut)(nil), "orderpb.LocalCut")
	proto.RegisterType((*LocalCuts)(nil), "orderpb.LocalCuts")
	proto.RegisterType((*CommittedCut)(nil), "orderpb.CommittedCut")
	proto.RegisterMapType((map[int32]int64)(nil), "orderpb.CommittedCut.CutEntry")
	proto.RegisterType((*CommittedEntry)(nil), "orderpb.CommittedEntry")
	proto.RegisterType((*FinalizeEntry)(nil), "orderpb.FinalizeEntry")
	proto.RegisterType((*Empty)(nil), "orderpb.Empty")
}

func init() { proto.RegisterFile("orderpb/order.proto", fileDescriptor_87a9833f63666870) }

var fileDescriptor_87a9833f63666870 = []byte{
	// 410 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x52, 0x5d, 0x8b, 0xd4, 0x30,
	0x14, 0x35, 0x93, 0xed, 0xb4, 0xde, 0x5d, 0x8b, 0x5e, 0x75, 0x2d, 0xf3, 0x20, 0xa5, 0xa0, 0xf4,
	0xa9, 0xae, 0x55, 0xc4, 0x0f, 0x10, 0x64, 0x76, 0x57, 0x16, 0x44, 0x21, 0xfb, 0x2e, 0x74, 0xdb,
	0x88, 0xc5, 0x76, 0x5a, 0x93, 0x74, 0x86, 0xf1, 0x77, 0xf8, 0x37, 0x7c, 0xf4, 0xff, 0x49, 0xd2,
	0x36, 0xcc, 0x97, 0x4f, 0xcd, 0xb9, 0x39, 0xe7, 0xde, 0x73, 0x72, 0x0b, 0xf7, 0x1b, 0x51, 0x70,
	0xd1, 0xde, 0x3c, 0x33, 0xdf, 0xa4, 0x15, 0x8d, 0x6a, 0xd0, 0x1d, 0x8a, 0xd1, 0x57, 0xf0, 0x3e,
	0x35, 0x79, 0x56, 0xcd, 0x3b, 0x85, 0x01, 0xb8, 0xf2, 0x7b, 0x26, 0x8a, 0xab, 0xf3, 0x80, 0x84,
	0x24, 0x76, 0xd8, 0x08, 0xf1, 0x29, 0xf8, 0x95, 0x66, 0x31, 0xde, 0x56, 0x65, 0x9e, 0x5d, 0x9d,
	0x07, 0x13, 0x43, 0xd8, 0xa9, 0xe2, 0x5d, 0xa0, 0x79, 0xa7, 0x02, 0x1a, 0xd2, 0x98, 0x32, 0x7d,
	0x8c, 0x52, 0xb8, 0x3d, 0xf6, 0x97, 0xf8, 0x04, 0x8e, 0xf2, 0x4e, 0xc9, 0x80, 0x84, 0x34, 0x3e,
	0x4e, 0xef, 0x25, 0x83, 0x89, 0x64, 0x64, 0x30, 0x73, 0x1d, 0xfd, 0x26, 0x70, 0x32, 0x6f, 0xea,
	0xba, 0x54, 0x8a, 0x17, 0xda, 0xd8, 0x0c, 0x3c, 0xa9, 0x32, 0xa1, 0x3e, 0x5e, 0x7f, 0x36, 0xce,
	0x28, 0xb3, 0x18, 0xcf, 0xfa, 0x91, 0x13, 0xd3, 0xf2, 0xb1, 0x6d, 0xb9, 0xa9, 0x4f, 0xe6, 0x9d,
	0xba, 0x58, 0x28, 0xb1, 0x36, 0x96, 0x66, 0xaf, 0xc0, 0x1b, 0x0b, 0xda, 0xf0, 0x0f, 0xbe, 0x1e,
	0xe2, 0xea, 0x23, 0x3e, 0x00, 0x67, 0x99, 0x55, 0x1d, 0x37, 0x09, 0x29, 0xeb, 0xc1, 0xdb, 0xc9,
	0x6b, 0x12, 0xfd, 0x25, 0xe0, 0xdb, 0xb6, 0x56, 0x2e, 0xf9, 0xcf, 0xc1, 0x93, 0x3e, 0xe2, 0x29,
	0x4c, 0x97, 0x25, 0x5f, 0xd9, 0x17, 0x1a, 0x10, 0xbe, 0x81, 0x93, 0x7c, 0xc3, 0x52, 0x40, 0x43,
	0x12, 0x1f, 0xa7, 0x0f, 0x0f, 0xfa, 0x65, 0x5b, 0x54, 0x7c, 0x0f, 0xfe, 0xb7, 0x72, 0x91, 0x55,
	0xe5, 0x2f, 0x7e, 0xad, 0xf7, 0x21, 0x83, 0x23, 0x23, 0x3e, 0xb5, 0xe2, 0xcb, 0xe1, 0xba, 0x0f,
	0xb9, 0xc3, 0x8e, 0x3e, 0xc0, 0x9d, 0x2d, 0x82, 0x8e, 0x58, 0x95, 0x75, 0xa9, 0x86, 0xd8, 0x3d,
	0x30, 0x8f, 0xdc, 0xaf, 0x5b, 0x9a, 0xd7, 0x74, 0x98, 0xc5, 0x91, 0x0b, 0xce, 0x45, 0xdd, 0xaa,
	0x75, 0xfa, 0x87, 0x80, 0xf3, 0x45, 0x4f, 0xc5, 0x77, 0x30, 0x65, 0xbc, 0x6d, 0x84, 0x42, 0xdc,
	0xdb, 0xa3, 0x9c, 0x3d, 0xda, 0x0f, 0x66, 0x66, 0x47, 0xb7, 0x62, 0x72, 0x46, 0xf0, 0x39, 0xb8,
	0x97, 0x8d, 0x58, 0x65, 0xa2, 0x38, 0xa8, 0xf6, 0x6d, 0xcd, 0x4c, 0xd5, 0x22, 0x7c, 0x09, 0xde,
	0x98, 0x02, 0xff, 0x93, 0x7c, 0x5f, 0x77, 0x33, 0x35, 0xbf, 0xfb, 0x8b, 0x7f, 0x01, 0x00, 0x00,
	0xff, 0xff, 0x9f, 0xde, 0xad, 0x91, 0x05, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// OrderClient is the client API for Order service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type OrderClient interface {
	Report(ctx context.Context, opts ...grpc.CallOption) (Order_ReportClient, error)
	Forward(ctx context.Context, opts ...grpc.CallOption) (Order_ForwardClient, error)
	Finalize(ctx context.Context, in *FinalizeEntry, opts ...grpc.CallOption) (*Empty, error)
}

type orderClient struct {
	cc *grpc.ClientConn
}

func NewOrderClient(cc *grpc.ClientConn) OrderClient {
	return &orderClient{cc}
}

func (c *orderClient) Report(ctx context.Context, opts ...grpc.CallOption) (Order_ReportClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Order_serviceDesc.Streams[0], "/orderpb.Order/Report", opts...)
	if err != nil {
		return nil, err
	}
	x := &orderReportClient{stream}
	return x, nil
}

type Order_ReportClient interface {
	Send(*LocalCuts) error
	Recv() (*CommittedEntry, error)
	grpc.ClientStream
}

type orderReportClient struct {
	grpc.ClientStream
}

func (x *orderReportClient) Send(m *LocalCuts) error {
	return x.ClientStream.SendMsg(m)
}

func (x *orderReportClient) Recv() (*CommittedEntry, error) {
	m := new(CommittedEntry)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *orderClient) Forward(ctx context.Context, opts ...grpc.CallOption) (Order_ForwardClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Order_serviceDesc.Streams[1], "/orderpb.Order/Forward", opts...)
	if err != nil {
		return nil, err
	}
	x := &orderForwardClient{stream}
	return x, nil
}

type Order_ForwardClient interface {
	Send(*LocalCuts) error
	CloseAndRecv() (*Empty, error)
	grpc.ClientStream
}

type orderForwardClient struct {
	grpc.ClientStream
}

func (x *orderForwardClient) Send(m *LocalCuts) error {
	return x.ClientStream.SendMsg(m)
}

func (x *orderForwardClient) CloseAndRecv() (*Empty, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(Empty)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *orderClient) Finalize(ctx context.Context, in *FinalizeEntry, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/orderpb.Order/Finalize", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrderServer is the server API for Order service.
type OrderServer interface {
	Report(Order_ReportServer) error
	Forward(Order_ForwardServer) error
	Finalize(context.Context, *FinalizeEntry) (*Empty, error)
}

func RegisterOrderServer(s *grpc.Server, srv OrderServer) {
	s.RegisterService(&_Order_serviceDesc, srv)
}

func _Order_Report_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(OrderServer).Report(&orderReportServer{stream})
}

type Order_ReportServer interface {
	Send(*CommittedEntry) error
	Recv() (*LocalCuts, error)
	grpc.ServerStream
}

type orderReportServer struct {
	grpc.ServerStream
}

func (x *orderReportServer) Send(m *CommittedEntry) error {
	return x.ServerStream.SendMsg(m)
}

func (x *orderReportServer) Recv() (*LocalCuts, error) {
	m := new(LocalCuts)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Order_Forward_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(OrderServer).Forward(&orderForwardServer{stream})
}

type Order_ForwardServer interface {
	SendAndClose(*Empty) error
	Recv() (*LocalCuts, error)
	grpc.ServerStream
}

type orderForwardServer struct {
	grpc.ServerStream
}

func (x *orderForwardServer) SendAndClose(m *Empty) error {
	return x.ServerStream.SendMsg(m)
}

func (x *orderForwardServer) Recv() (*LocalCuts, error) {
	m := new(LocalCuts)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Order_Finalize_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FinalizeEntry)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServer).Finalize(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/orderpb.Order/Finalize",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServer).Finalize(ctx, req.(*FinalizeEntry))
	}
	return interceptor(ctx, in, info, handler)
}

var _Order_serviceDesc = grpc.ServiceDesc{
	ServiceName: "orderpb.Order",
	HandlerType: (*OrderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Finalize",
			Handler:    _Order_Finalize_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Report",
			Handler:       _Order_Report_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "Forward",
			Handler:       _Order_Forward_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "orderpb/order.proto",
}
