// Code generated by protoc-gen-go.
// source: orderpb/order.proto
// DO NOT EDIT!

/*
Package orderpb is a generated protocol buffer package.

It is generated from these files:
	orderpb/order.proto

It has these top-level messages:
	LocalCut
	LocalCuts
	CommittedCut
	CommittedEntry
	FinalizeEntry
	Empty
*/
package orderpb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type LocalCut struct {
	ShardID        int32   `protobuf:"varint,1,opt,name=shardID" json:"shardID,omitempty"`
	LocalReplicaID int32   `protobuf:"varint,2,opt,name=localReplicaID" json:"localReplicaID,omitempty"`
	Cut            []int64 `protobuf:"varint,3,rep,packed,name=cut" json:"cut,omitempty"`
}

func (m *LocalCut) Reset()                    { *m = LocalCut{} }
func (m *LocalCut) String() string            { return proto.CompactTextString(m) }
func (*LocalCut) ProtoMessage()               {}
func (*LocalCut) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *LocalCut) GetShardID() int32 {
	if m != nil {
		return m.ShardID
	}
	return 0
}

func (m *LocalCut) GetLocalReplicaID() int32 {
	if m != nil {
		return m.LocalReplicaID
	}
	return 0
}

func (m *LocalCut) GetCut() []int64 {
	if m != nil {
		return m.Cut
	}
	return nil
}

type LocalCuts struct {
	Cuts []*LocalCut `protobuf:"bytes,1,rep,name=cuts" json:"cuts,omitempty"`
}

func (m *LocalCuts) Reset()                    { *m = LocalCuts{} }
func (m *LocalCuts) String() string            { return proto.CompactTextString(m) }
func (*LocalCuts) ProtoMessage()               {}
func (*LocalCuts) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *LocalCuts) GetCuts() []*LocalCut {
	if m != nil {
		return m.Cuts
	}
	return nil
}

type CommittedCut struct {
	StartGSN int32 `protobuf:"varint,1,opt,name=startGSN" json:"startGSN,omitempty"`
	// from globalReplicaID to each cut entry
	// globalReplicaID = shardID * numReplicas + localReplicaID
	Cut map[int32]int64 `protobuf:"bytes,2,rep,name=cut" json:"cut,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
}

func (m *CommittedCut) Reset()                    { *m = CommittedCut{} }
func (m *CommittedCut) String() string            { return proto.CompactTextString(m) }
func (*CommittedCut) ProtoMessage()               {}
func (*CommittedCut) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *CommittedCut) GetStartGSN() int32 {
	if m != nil {
		return m.StartGSN
	}
	return 0
}

func (m *CommittedCut) GetCut() map[int32]int64 {
	if m != nil {
		return m.Cut
	}
	return nil
}

type CommittedEntry struct {
	Seq            int64          `protobuf:"varint,1,opt,name=seq" json:"seq,omitempty"`
	ViewID         int32          `protobuf:"varint,2,opt,name=viewID" json:"viewID,omitempty"`
	CommittedCut   *CommittedCut  `protobuf:"bytes,3,opt,name=committedCut" json:"committedCut,omitempty"`
	FinalizeShards *FinalizeEntry `protobuf:"bytes,4,opt,name=finalizeShards" json:"finalizeShards,omitempty"`
}

func (m *CommittedEntry) Reset()                    { *m = CommittedEntry{} }
func (m *CommittedEntry) String() string            { return proto.CompactTextString(m) }
func (*CommittedEntry) ProtoMessage()               {}
func (*CommittedEntry) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *CommittedEntry) GetSeq() int64 {
	if m != nil {
		return m.Seq
	}
	return 0
}

func (m *CommittedEntry) GetViewID() int32 {
	if m != nil {
		return m.ViewID
	}
	return 0
}

func (m *CommittedEntry) GetCommittedCut() *CommittedCut {
	if m != nil {
		return m.CommittedCut
	}
	return nil
}

func (m *CommittedEntry) GetFinalizeShards() *FinalizeEntry {
	if m != nil {
		return m.FinalizeShards
	}
	return nil
}

type FinalizeEntry struct {
	Limit    int32   `protobuf:"varint,1,opt,name=limit" json:"limit,omitempty"`
	ShardIDs []int32 `protobuf:"varint,2,rep,packed,name=shardIDs" json:"shardIDs,omitempty"`
}

func (m *FinalizeEntry) Reset()                    { *m = FinalizeEntry{} }
func (m *FinalizeEntry) String() string            { return proto.CompactTextString(m) }
func (*FinalizeEntry) ProtoMessage()               {}
func (*FinalizeEntry) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *FinalizeEntry) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *FinalizeEntry) GetShardIDs() []int32 {
	if m != nil {
		return m.ShardIDs
	}
	return nil
}

type Empty struct {
}

func (m *Empty) Reset()                    { *m = Empty{} }
func (m *Empty) String() string            { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()               {}
func (*Empty) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func init() {
	proto.RegisterType((*LocalCut)(nil), "orderpb.LocalCut")
	proto.RegisterType((*LocalCuts)(nil), "orderpb.LocalCuts")
	proto.RegisterType((*CommittedCut)(nil), "orderpb.CommittedCut")
	proto.RegisterType((*CommittedEntry)(nil), "orderpb.CommittedEntry")
	proto.RegisterType((*FinalizeEntry)(nil), "orderpb.FinalizeEntry")
	proto.RegisterType((*Empty)(nil), "orderpb.Empty")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Order service

type OrderClient interface {
	Report(ctx context.Context, opts ...grpc.CallOption) (Order_ReportClient, error)
	Forward(ctx context.Context, opts ...grpc.CallOption) (Order_ForwardClient, error)
	Finalize(ctx context.Context, in *FinalizeEntry, opts ...grpc.CallOption) (*Empty, error)
}

type orderClient struct {
	cc *grpc.ClientConn
}

func NewOrderClient(cc *grpc.ClientConn) OrderClient {
	return &orderClient{cc}
}

func (c *orderClient) Report(ctx context.Context, opts ...grpc.CallOption) (Order_ReportClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Order_serviceDesc.Streams[0], c.cc, "/orderpb.Order/Report", opts...)
	if err != nil {
		return nil, err
	}
	x := &orderReportClient{stream}
	return x, nil
}

type Order_ReportClient interface {
	Send(*LocalCuts) error
	Recv() (*CommittedEntry, error)
	grpc.ClientStream
}

type orderReportClient struct {
	grpc.ClientStream
}

func (x *orderReportClient) Send(m *LocalCuts) error {
	return x.ClientStream.SendMsg(m)
}

func (x *orderReportClient) Recv() (*CommittedEntry, error) {
	m := new(CommittedEntry)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *orderClient) Forward(ctx context.Context, opts ...grpc.CallOption) (Order_ForwardClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Order_serviceDesc.Streams[1], c.cc, "/orderpb.Order/Forward", opts...)
	if err != nil {
		return nil, err
	}
	x := &orderForwardClient{stream}
	return x, nil
}

type Order_ForwardClient interface {
	Send(*LocalCuts) error
	CloseAndRecv() (*Empty, error)
	grpc.ClientStream
}

type orderForwardClient struct {
	grpc.ClientStream
}

func (x *orderForwardClient) Send(m *LocalCuts) error {
	return x.ClientStream.SendMsg(m)
}

func (x *orderForwardClient) CloseAndRecv() (*Empty, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(Empty)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *orderClient) Finalize(ctx context.Context, in *FinalizeEntry, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := grpc.Invoke(ctx, "/orderpb.Order/Finalize", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Order service

type OrderServer interface {
	Report(Order_ReportServer) error
	Forward(Order_ForwardServer) error
	Finalize(context.Context, *FinalizeEntry) (*Empty, error)
}

func RegisterOrderServer(s *grpc.Server, srv OrderServer) {
	s.RegisterService(&_Order_serviceDesc, srv)
}

func _Order_Report_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(OrderServer).Report(&orderReportServer{stream})
}

type Order_ReportServer interface {
	Send(*CommittedEntry) error
	Recv() (*LocalCuts, error)
	grpc.ServerStream
}

type orderReportServer struct {
	grpc.ServerStream
}

func (x *orderReportServer) Send(m *CommittedEntry) error {
	return x.ServerStream.SendMsg(m)
}

func (x *orderReportServer) Recv() (*LocalCuts, error) {
	m := new(LocalCuts)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Order_Forward_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(OrderServer).Forward(&orderForwardServer{stream})
}

type Order_ForwardServer interface {
	SendAndClose(*Empty) error
	Recv() (*LocalCuts, error)
	grpc.ServerStream
}

type orderForwardServer struct {
	grpc.ServerStream
}

func (x *orderForwardServer) SendAndClose(m *Empty) error {
	return x.ServerStream.SendMsg(m)
}

func (x *orderForwardServer) Recv() (*LocalCuts, error) {
	m := new(LocalCuts)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Order_Finalize_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FinalizeEntry)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServer).Finalize(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/orderpb.Order/Finalize",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServer).Finalize(ctx, req.(*FinalizeEntry))
	}
	return interceptor(ctx, in, info, handler)
}

var _Order_serviceDesc = grpc.ServiceDesc{
	ServiceName: "orderpb.Order",
	HandlerType: (*OrderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Finalize",
			Handler:    _Order_Finalize_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Report",
			Handler:       _Order_Report_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "Forward",
			Handler:       _Order_Forward_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "orderpb/order.proto",
}

func init() { proto.RegisterFile("orderpb/order.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 410 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x74, 0x52, 0x5d, 0x8b, 0xd4, 0x30,
	0x14, 0x35, 0x93, 0xed, 0xb4, 0xde, 0x5d, 0x8b, 0x5e, 0x75, 0x2d, 0xf3, 0x20, 0xa5, 0xa0, 0xf4,
	0xa9, 0xae, 0x55, 0xc4, 0x0f, 0x10, 0x64, 0x76, 0x57, 0x16, 0x44, 0x21, 0xfb, 0x2e, 0x74, 0xdb,
	0x88, 0xc5, 0x76, 0x5a, 0x93, 0x74, 0x86, 0xf1, 0x77, 0xf8, 0x37, 0x7c, 0xf4, 0xff, 0x49, 0xd2,
	0xb4, 0xcc, 0x97, 0x4f, 0xcd, 0xb9, 0x39, 0xe7, 0xde, 0x73, 0x6e, 0x0a, 0xf7, 0x1b, 0x51, 0x70,
	0xd1, 0xde, 0x3c, 0x33, 0xdf, 0xa4, 0x15, 0x8d, 0x6a, 0xd0, 0xb5, 0xc5, 0xe8, 0x2b, 0x78, 0x9f,
	0x9a, 0x3c, 0xab, 0xe6, 0x9d, 0xc2, 0x00, 0x5c, 0xf9, 0x3d, 0x13, 0xc5, 0xd5, 0x79, 0x40, 0x42,
	0x12, 0x3b, 0x6c, 0x80, 0xf8, 0x14, 0xfc, 0x4a, 0xb3, 0x18, 0x6f, 0xab, 0x32, 0xcf, 0xae, 0xce,
	0x83, 0x89, 0x21, 0xec, 0x54, 0xf1, 0x2e, 0xd0, 0xbc, 0x53, 0x01, 0x0d, 0x69, 0x4c, 0x99, 0x3e,
	0x46, 0x29, 0xdc, 0x1e, 0xfa, 0x4b, 0x7c, 0x02, 0x47, 0x79, 0xa7, 0x64, 0x40, 0x42, 0x1a, 0x1f,
	0xa7, 0xf7, 0x12, 0x6b, 0x22, 0x19, 0x18, 0xcc, 0x5c, 0x47, 0xbf, 0x09, 0x9c, 0xcc, 0x9b, 0xba,
	0x2e, 0x95, 0xe2, 0x85, 0x36, 0x36, 0x03, 0x4f, 0xaa, 0x4c, 0xa8, 0x8f, 0xd7, 0x9f, 0xad, 0xb3,
	0x11, 0xe3, 0x59, 0x3f, 0x72, 0x62, 0x5a, 0x3e, 0x1e, 0x5b, 0x6e, 0xea, 0x93, 0x79, 0xa7, 0x2e,
	0x16, 0x4a, 0xac, 0x8d, 0xa5, 0xd9, 0x2b, 0xf0, 0x86, 0x82, 0x36, 0xfc, 0x83, 0xaf, 0x6d, 0x53,
	0x7d, 0xc4, 0x07, 0xe0, 0x2c, 0xb3, 0xaa, 0xe3, 0x26, 0x21, 0x65, 0x3d, 0x78, 0x3b, 0x79, 0x4d,
	0xa2, 0xbf, 0x04, 0xfc, 0xb1, 0xed, 0x28, 0x97, 0xfc, 0xa7, 0x91, 0x53, 0xa6, 0x8f, 0x78, 0x0a,
	0xd3, 0x65, 0xc9, 0x57, 0xe3, 0x86, 0x2c, 0xc2, 0x37, 0x70, 0x92, 0x6f, 0x58, 0x0a, 0x68, 0x48,
	0xe2, 0xe3, 0xf4, 0xe1, 0x41, 0xbf, 0x6c, 0x8b, 0x8a, 0xef, 0xc1, 0xff, 0x56, 0x2e, 0xb2, 0xaa,
	0xfc, 0xc5, 0xaf, 0xf5, 0x7b, 0xc8, 0xe0, 0xc8, 0x88, 0x4f, 0x47, 0xf1, 0xa5, 0xbd, 0xee, 0x43,
	0xee, 0xb0, 0xa3, 0x0f, 0x70, 0x67, 0x8b, 0xa0, 0x23, 0x56, 0x65, 0x5d, 0x2a, 0x1b, 0xbb, 0x07,
	0x66, 0xc9, 0xfd, 0x73, 0x4b, 0xb3, 0x4d, 0xbd, 0x64, 0x8b, 0x23, 0x17, 0x9c, 0x8b, 0xba, 0x55,
	0xeb, 0xf4, 0x0f, 0x01, 0xe7, 0x8b, 0x9e, 0x8a, 0xef, 0x60, 0xca, 0x78, 0xdb, 0x08, 0x85, 0xb8,
	0xf7, 0x8e, 0x72, 0xf6, 0x68, 0x3f, 0x98, 0x99, 0x1d, 0xdd, 0x8a, 0xc9, 0x19, 0xc1, 0xe7, 0xe0,
	0x5e, 0x36, 0x62, 0x95, 0x89, 0xe2, 0xa0, 0xda, 0x1f, 0x6b, 0x66, 0xaa, 0x16, 0xe1, 0x4b, 0xf0,
	0x86, 0x14, 0xf8, 0x9f, 0xe4, 0xfb, 0xba, 0x9b, 0xa9, 0xf9, 0xdd, 0x5f, 0xfc, 0x0b, 0x00, 0x00,
	0xff, 0xff, 0xb6, 0x23, 0xaf, 0xda, 0x05, 0x03, 0x00, 0x00,
}
