// Code generated by protoc-gen-go. DO NOT EDIT.
// source: datapb/data.proto

package datapb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Record struct {
	ClientID             int32    `protobuf:"varint,1,opt,name=clientID,proto3" json:"clientID,omitempty"`
	ClientSN             int32    `protobuf:"varint,2,opt,name=clientSN,proto3" json:"clientSN,omitempty"`
	ShardID              int32    `protobuf:"varint,3,opt,name=shardID,proto3" json:"shardID,omitempty"`
	LocalReplicaID       int32    `protobuf:"varint,4,opt,name=localReplicaID,proto3" json:"localReplicaID,omitempty"`
	ViewID               int32    `protobuf:"varint,5,opt,name=viewID,proto3" json:"viewID,omitempty"`
	GlobalSN             int64    `protobuf:"varint,6,opt,name=globalSN,proto3" json:"globalSN,omitempty"`
	Record               string   `protobuf:"bytes,7,opt,name=record,proto3" json:"record,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Record) Reset()         { *m = Record{} }
func (m *Record) String() string { return proto.CompactTextString(m) }
func (*Record) ProtoMessage()    {}
func (*Record) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb12a5d0dd175b31, []int{0}
}

func (m *Record) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Record.Unmarshal(m, b)
}
func (m *Record) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Record.Marshal(b, m, deterministic)
}
func (m *Record) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Record.Merge(m, src)
}
func (m *Record) XXX_Size() int {
	return xxx_messageInfo_Record.Size(m)
}
func (m *Record) XXX_DiscardUnknown() {
	xxx_messageInfo_Record.DiscardUnknown(m)
}

var xxx_messageInfo_Record proto.InternalMessageInfo

func (m *Record) GetClientID() int32 {
	if m != nil {
		return m.ClientID
	}
	return 0
}

func (m *Record) GetClientSN() int32 {
	if m != nil {
		return m.ClientSN
	}
	return 0
}

func (m *Record) GetShardID() int32 {
	if m != nil {
		return m.ShardID
	}
	return 0
}

func (m *Record) GetLocalReplicaID() int32 {
	if m != nil {
		return m.LocalReplicaID
	}
	return 0
}

func (m *Record) GetViewID() int32 {
	if m != nil {
		return m.ViewID
	}
	return 0
}

func (m *Record) GetGlobalSN() int64 {
	if m != nil {
		return m.GlobalSN
	}
	return 0
}

func (m *Record) GetRecord() string {
	if m != nil {
		return m.Record
	}
	return ""
}

type Ack struct {
	ClientID             int32    `protobuf:"varint,1,opt,name=clientID,proto3" json:"clientID,omitempty"`
	ClientSN             int32    `protobuf:"varint,2,opt,name=clientSN,proto3" json:"clientSN,omitempty"`
	ShardID              int32    `protobuf:"varint,3,opt,name=shardID,proto3" json:"shardID,omitempty"`
	LocalReplicaID       int32    `protobuf:"varint,4,opt,name=localReplicaID,proto3" json:"localReplicaID,omitempty"`
	ViewID               int32    `protobuf:"varint,5,opt,name=viewID,proto3" json:"viewID,omitempty"`
	GlobalSN             int64    `protobuf:"varint,6,opt,name=globalSN,proto3" json:"globalSN,omitempty"`
	Succeeded            bool     `protobuf:"varint,7,opt,name=succeeded,proto3" json:"succeeded,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Ack) Reset()         { *m = Ack{} }
func (m *Ack) String() string { return proto.CompactTextString(m) }
func (*Ack) ProtoMessage()    {}
func (*Ack) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb12a5d0dd175b31, []int{1}
}

func (m *Ack) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ack.Unmarshal(m, b)
}
func (m *Ack) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ack.Marshal(b, m, deterministic)
}
func (m *Ack) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ack.Merge(m, src)
}
func (m *Ack) XXX_Size() int {
	return xxx_messageInfo_Ack.Size(m)
}
func (m *Ack) XXX_DiscardUnknown() {
	xxx_messageInfo_Ack.DiscardUnknown(m)
}

var xxx_messageInfo_Ack proto.InternalMessageInfo

func (m *Ack) GetClientID() int32 {
	if m != nil {
		return m.ClientID
	}
	return 0
}

func (m *Ack) GetClientSN() int32 {
	if m != nil {
		return m.ClientSN
	}
	return 0
}

func (m *Ack) GetShardID() int32 {
	if m != nil {
		return m.ShardID
	}
	return 0
}

func (m *Ack) GetLocalReplicaID() int32 {
	if m != nil {
		return m.LocalReplicaID
	}
	return 0
}

func (m *Ack) GetViewID() int32 {
	if m != nil {
		return m.ViewID
	}
	return 0
}

func (m *Ack) GetGlobalSN() int64 {
	if m != nil {
		return m.GlobalSN
	}
	return 0
}

func (m *Ack) GetSucceeded() bool {
	if m != nil {
		return m.Succeeded
	}
	return false
}

type GlobalSN struct {
	Gsn                  int64    `protobuf:"varint,1,opt,name=gsn,proto3" json:"gsn,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GlobalSN) Reset()         { *m = GlobalSN{} }
func (m *GlobalSN) String() string { return proto.CompactTextString(m) }
func (*GlobalSN) ProtoMessage()    {}
func (*GlobalSN) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb12a5d0dd175b31, []int{2}
}

func (m *GlobalSN) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GlobalSN.Unmarshal(m, b)
}
func (m *GlobalSN) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GlobalSN.Marshal(b, m, deterministic)
}
func (m *GlobalSN) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GlobalSN.Merge(m, src)
}
func (m *GlobalSN) XXX_Size() int {
	return xxx_messageInfo_GlobalSN.Size(m)
}
func (m *GlobalSN) XXX_DiscardUnknown() {
	xxx_messageInfo_GlobalSN.DiscardUnknown(m)
}

var xxx_messageInfo_GlobalSN proto.InternalMessageInfo

func (m *GlobalSN) GetGsn() int64 {
	if m != nil {
		return m.Gsn
	}
	return 0
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb12a5d0dd175b31, []int{3}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Record)(nil), "datapb.Record")
	proto.RegisterType((*Ack)(nil), "datapb.Ack")
	proto.RegisterType((*GlobalSN)(nil), "datapb.GlobalSN")
	proto.RegisterType((*Empty)(nil), "datapb.Empty")
}

func init() { proto.RegisterFile("datapb/data.proto", fileDescriptor_eb12a5d0dd175b31) }

var fileDescriptor_eb12a5d0dd175b31 = []byte{
	// 341 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xd4, 0x92, 0xc1, 0x4a, 0xfb, 0x40,
	0x10, 0xc6, 0xbb, 0x4d, 0x9a, 0x36, 0xf3, 0xe7, 0x5f, 0xea, 0x1c, 0x64, 0x29, 0x3d, 0x94, 0x1c,
	0x34, 0x54, 0x88, 0x55, 0x9f, 0xa0, 0x10, 0x91, 0x5c, 0x2a, 0x6c, 0x7c, 0x81, 0xcd, 0x66, 0xa9,
	0xa1, 0x69, 0x12, 0x92, 0x54, 0xf1, 0x49, 0x7c, 0x2b, 0xc1, 0x37, 0x92, 0x6c, 0xba, 0xad, 0x54,
	0x41, 0xaf, 0x9e, 0x92, 0xdf, 0x7c, 0xdf, 0xce, 0xce, 0xc7, 0x2c, 0x9c, 0xc4, 0xbc, 0xe6, 0x45,
	0x74, 0xd9, 0x7c, 0xbc, 0xa2, 0xcc, 0xeb, 0x1c, 0xad, 0xb6, 0xe4, 0xbc, 0x11, 0xb0, 0x98, 0x14,
	0x79, 0x19, 0xe3, 0x18, 0x06, 0x22, 0x4d, 0x64, 0x56, 0x07, 0x3e, 0x25, 0x53, 0xe2, 0xf6, 0xd8,
	0x9e, 0x0f, 0x5a, 0xb8, 0xa4, 0xdd, 0xcf, 0x5a, 0xb8, 0x44, 0x0a, 0xfd, 0xea, 0x91, 0x97, 0x71,
	0xe0, 0x53, 0x43, 0x49, 0x1a, 0xf1, 0x0c, 0x86, 0x69, 0x2e, 0x78, 0xca, 0x64, 0x91, 0x26, 0x82,
	0x07, 0x3e, 0x35, 0x95, 0xe1, 0xa8, 0x8a, 0xa7, 0x60, 0x3d, 0x25, 0xf2, 0x39, 0xf0, 0x69, 0x4f,
	0xe9, 0x3b, 0x6a, 0x6e, 0x5d, 0xa5, 0x79, 0xc4, 0xd3, 0x70, 0x49, 0xad, 0x29, 0x71, 0x0d, 0xb6,
	0xe7, 0xe6, 0x4c, 0xa9, 0xe6, 0xa6, 0xfd, 0x29, 0x71, 0x6d, 0xb6, 0x23, 0xe7, 0x9d, 0x80, 0xb1,
	0x10, 0xeb, 0x3f, 0x96, 0x66, 0x02, 0x76, 0xb5, 0x15, 0x42, 0xca, 0x58, 0xb6, 0x81, 0x06, 0xec,
	0x50, 0x70, 0x26, 0x30, 0xb8, 0xd3, 0xce, 0x11, 0x18, 0xab, 0x2a, 0x53, 0x91, 0x0c, 0xd6, 0xfc,
	0x3a, 0x7d, 0xe8, 0xdd, 0x6e, 0x8a, 0xfa, 0xe5, 0xfa, 0xb5, 0x0b, 0xa6, 0xcf, 0x6b, 0x8e, 0x17,
	0x60, 0x2d, 0x8a, 0x42, 0x66, 0x31, 0x0e, 0xbd, 0x76, 0xcf, 0x5e, 0xbb, 0xe3, 0xf1, 0x3f, 0xcd,
	0x0b, 0xb1, 0x76, 0x3a, 0x2e, 0x99, 0x13, 0x9c, 0x81, 0xdd, 0x9a, 0xef, 0x33, 0xf9, 0x83, 0x1f,
	0x3d, 0xb0, 0x77, 0x39, 0xeb, 0xaf, 0xde, 0xff, 0x9a, 0xd5, 0x34, 0x4d, 0x77, 0xbc, 0x02, 0x3b,
	0xdc, 0x46, 0x95, 0x28, 0x93, 0x48, 0xe2, 0x48, 0xeb, 0x3a, 0xcb, 0xf8, 0xa8, 0x83, 0xd3, 0x99,
	0x13, 0x3c, 0x07, 0xf3, 0xa1, 0x4c, 0x36, 0xdf, 0xb8, 0x8f, 0x66, 0x99, 0x81, 0xc9, 0x24, 0x8f,
	0x7f, 0xd3, 0x36, 0xb2, 0xd4, 0xa3, 0xbf, 0xf9, 0x08, 0x00, 0x00, 0xff, 0xff, 0x34, 0xa5, 0x93,
	0x8f, 0x09, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DataClient is the client API for Data service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DataClient interface {
	// clients set shardID to -1
	Append(ctx context.Context, opts ...grpc.CallOption) (Data_AppendClient, error)
	AppendOne(ctx context.Context, in *Record, opts ...grpc.CallOption) (*Ack, error)
	// replicas set proper shardID and localReplicaID
	Replicate(ctx context.Context, opts ...grpc.CallOption) (Data_ReplicateClient, error)
	// the servers don't need to know the sources of the following requests
	Subscribe(ctx context.Context, in *GlobalSN, opts ...grpc.CallOption) (Data_SubscribeClient, error)
	Trim(ctx context.Context, in *GlobalSN, opts ...grpc.CallOption) (*Ack, error)
	Read(ctx context.Context, in *GlobalSN, opts ...grpc.CallOption) (*Record, error)
}

type dataClient struct {
	cc *grpc.ClientConn
}

func NewDataClient(cc *grpc.ClientConn) DataClient {
	return &dataClient{cc}
}

func (c *dataClient) Append(ctx context.Context, opts ...grpc.CallOption) (Data_AppendClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Data_serviceDesc.Streams[0], "/datapb.Data/Append", opts...)
	if err != nil {
		return nil, err
	}
	x := &dataAppendClient{stream}
	return x, nil
}

type Data_AppendClient interface {
	Send(*Record) error
	Recv() (*Ack, error)
	grpc.ClientStream
}

type dataAppendClient struct {
	grpc.ClientStream
}

func (x *dataAppendClient) Send(m *Record) error {
	return x.ClientStream.SendMsg(m)
}

func (x *dataAppendClient) Recv() (*Ack, error) {
	m := new(Ack)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *dataClient) AppendOne(ctx context.Context, in *Record, opts ...grpc.CallOption) (*Ack, error) {
	out := new(Ack)
	err := c.cc.Invoke(ctx, "/datapb.Data/AppendOne", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataClient) Replicate(ctx context.Context, opts ...grpc.CallOption) (Data_ReplicateClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Data_serviceDesc.Streams[1], "/datapb.Data/Replicate", opts...)
	if err != nil {
		return nil, err
	}
	x := &dataReplicateClient{stream}
	return x, nil
}

type Data_ReplicateClient interface {
	Send(*Record) error
	CloseAndRecv() (*Empty, error)
	grpc.ClientStream
}

type dataReplicateClient struct {
	grpc.ClientStream
}

func (x *dataReplicateClient) Send(m *Record) error {
	return x.ClientStream.SendMsg(m)
}

func (x *dataReplicateClient) CloseAndRecv() (*Empty, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(Empty)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *dataClient) Subscribe(ctx context.Context, in *GlobalSN, opts ...grpc.CallOption) (Data_SubscribeClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Data_serviceDesc.Streams[2], "/datapb.Data/Subscribe", opts...)
	if err != nil {
		return nil, err
	}
	x := &dataSubscribeClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Data_SubscribeClient interface {
	Recv() (*Record, error)
	grpc.ClientStream
}

type dataSubscribeClient struct {
	grpc.ClientStream
}

func (x *dataSubscribeClient) Recv() (*Record, error) {
	m := new(Record)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *dataClient) Trim(ctx context.Context, in *GlobalSN, opts ...grpc.CallOption) (*Ack, error) {
	out := new(Ack)
	err := c.cc.Invoke(ctx, "/datapb.Data/Trim", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataClient) Read(ctx context.Context, in *GlobalSN, opts ...grpc.CallOption) (*Record, error) {
	out := new(Record)
	err := c.cc.Invoke(ctx, "/datapb.Data/Read", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DataServer is the server API for Data service.
type DataServer interface {
	// clients set shardID to -1
	Append(Data_AppendServer) error
	AppendOne(context.Context, *Record) (*Ack, error)
	// replicas set proper shardID and localReplicaID
	Replicate(Data_ReplicateServer) error
	// the servers don't need to know the sources of the following requests
	Subscribe(*GlobalSN, Data_SubscribeServer) error
	Trim(context.Context, *GlobalSN) (*Ack, error)
	Read(context.Context, *GlobalSN) (*Record, error)
}

func RegisterDataServer(s *grpc.Server, srv DataServer) {
	s.RegisterService(&_Data_serviceDesc, srv)
}

func _Data_Append_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DataServer).Append(&dataAppendServer{stream})
}

type Data_AppendServer interface {
	Send(*Ack) error
	Recv() (*Record, error)
	grpc.ServerStream
}

type dataAppendServer struct {
	grpc.ServerStream
}

func (x *dataAppendServer) Send(m *Ack) error {
	return x.ServerStream.SendMsg(m)
}

func (x *dataAppendServer) Recv() (*Record, error) {
	m := new(Record)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Data_AppendOne_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Record)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataServer).AppendOne(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/datapb.Data/AppendOne",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataServer).AppendOne(ctx, req.(*Record))
	}
	return interceptor(ctx, in, info, handler)
}

func _Data_Replicate_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DataServer).Replicate(&dataReplicateServer{stream})
}

type Data_ReplicateServer interface {
	SendAndClose(*Empty) error
	Recv() (*Record, error)
	grpc.ServerStream
}

type dataReplicateServer struct {
	grpc.ServerStream
}

func (x *dataReplicateServer) SendAndClose(m *Empty) error {
	return x.ServerStream.SendMsg(m)
}

func (x *dataReplicateServer) Recv() (*Record, error) {
	m := new(Record)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Data_Subscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GlobalSN)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DataServer).Subscribe(m, &dataSubscribeServer{stream})
}

type Data_SubscribeServer interface {
	Send(*Record) error
	grpc.ServerStream
}

type dataSubscribeServer struct {
	grpc.ServerStream
}

func (x *dataSubscribeServer) Send(m *Record) error {
	return x.ServerStream.SendMsg(m)
}

func _Data_Trim_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GlobalSN)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataServer).Trim(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/datapb.Data/Trim",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataServer).Trim(ctx, req.(*GlobalSN))
	}
	return interceptor(ctx, in, info, handler)
}

func _Data_Read_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GlobalSN)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataServer).Read(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/datapb.Data/Read",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataServer).Read(ctx, req.(*GlobalSN))
	}
	return interceptor(ctx, in, info, handler)
}

var _Data_serviceDesc = grpc.ServiceDesc{
	ServiceName: "datapb.Data",
	HandlerType: (*DataServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AppendOne",
			Handler:    _Data_AppendOne_Handler,
		},
		{
			MethodName: "Trim",
			Handler:    _Data_Trim_Handler,
		},
		{
			MethodName: "Read",
			Handler:    _Data_Read_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Append",
			Handler:       _Data_Append_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "Replicate",
			Handler:       _Data_Replicate_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "Subscribe",
			Handler:       _Data_Subscribe_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "datapb/data.proto",
}
